# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Hunter Peart/CS5030/class-project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Hunter Peart/CS5030/class-project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Hunter Peart/CS5030/class-project/CMakeFiles" "/mnt/c/Users/Hunter Peart/CS5030/class-project//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Hunter Peart/CS5030/class-project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named class_project

# Build rule for target.
class_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 class_project
.PHONY : class_project

# fast build rule for target.
class_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/build
.PHONY : class_project/fast

#=============================================================================
# Target rules for targets named gpu

# Build rule for target.
gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpu
.PHONY : gpu

# fast build rule for target.
gpu/fast:
	$(MAKE) $(MAKESILENT) -f gpu/CMakeFiles/gpu.dir/build.make gpu/CMakeFiles/gpu.dir/build
.PHONY : gpu/fast

src/AlgorithmFactory.o: src/AlgorithmFactory.cpp.o
.PHONY : src/AlgorithmFactory.o

# target to build an object file
src/AlgorithmFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/AlgorithmFactory.cpp.o
.PHONY : src/AlgorithmFactory.cpp.o

src/AlgorithmFactory.i: src/AlgorithmFactory.cpp.i
.PHONY : src/AlgorithmFactory.i

# target to preprocess a source file
src/AlgorithmFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/AlgorithmFactory.cpp.i
.PHONY : src/AlgorithmFactory.cpp.i

src/AlgorithmFactory.s: src/AlgorithmFactory.cpp.s
.PHONY : src/AlgorithmFactory.s

# target to generate assembly for a file
src/AlgorithmFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/AlgorithmFactory.cpp.s
.PHONY : src/AlgorithmFactory.cpp.s

src/SpotifyFrameUtils.o: src/SpotifyFrameUtils.cpp.o
.PHONY : src/SpotifyFrameUtils.o

# target to build an object file
src/SpotifyFrameUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/SpotifyFrameUtils.cpp.o
.PHONY : src/SpotifyFrameUtils.cpp.o

src/SpotifyFrameUtils.i: src/SpotifyFrameUtils.cpp.i
.PHONY : src/SpotifyFrameUtils.i

# target to preprocess a source file
src/SpotifyFrameUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/SpotifyFrameUtils.cpp.i
.PHONY : src/SpotifyFrameUtils.cpp.i

src/SpotifyFrameUtils.s: src/SpotifyFrameUtils.cpp.s
.PHONY : src/SpotifyFrameUtils.s

# target to generate assembly for a file
src/SpotifyFrameUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/SpotifyFrameUtils.cpp.s
.PHONY : src/SpotifyFrameUtils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tools/SpotifyFrameReader.o: tools/SpotifyFrameReader.cpp.o
.PHONY : tools/SpotifyFrameReader.o

# target to build an object file
tools/SpotifyFrameReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/tools/SpotifyFrameReader.cpp.o
.PHONY : tools/SpotifyFrameReader.cpp.o

tools/SpotifyFrameReader.i: tools/SpotifyFrameReader.cpp.i
.PHONY : tools/SpotifyFrameReader.i

# target to preprocess a source file
tools/SpotifyFrameReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/tools/SpotifyFrameReader.cpp.i
.PHONY : tools/SpotifyFrameReader.cpp.i

tools/SpotifyFrameReader.s: tools/SpotifyFrameReader.cpp.s
.PHONY : tools/SpotifyFrameReader.s

# target to generate assembly for a file
tools/SpotifyFrameReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/tools/SpotifyFrameReader.cpp.s
.PHONY : tools/SpotifyFrameReader.cpp.s

tools/utils.o: tools/utils.cpp.o
.PHONY : tools/utils.o

# target to build an object file
tools/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/tools/utils.cpp.o
.PHONY : tools/utils.cpp.o

tools/utils.i: tools/utils.cpp.i
.PHONY : tools/utils.i

# target to preprocess a source file
tools/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/tools/utils.cpp.i
.PHONY : tools/utils.cpp.i

tools/utils.s: tools/utils.cpp.s
.PHONY : tools/utils.s

# target to generate assembly for a file
tools/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/class_project.dir/build.make CMakeFiles/class_project.dir/tools/utils.cpp.s
.PHONY : tools/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... class_project"
	@echo "... gpu"
	@echo "... src/AlgorithmFactory.o"
	@echo "... src/AlgorithmFactory.i"
	@echo "... src/AlgorithmFactory.s"
	@echo "... src/SpotifyFrameUtils.o"
	@echo "... src/SpotifyFrameUtils.i"
	@echo "... src/SpotifyFrameUtils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tools/SpotifyFrameReader.o"
	@echo "... tools/SpotifyFrameReader.i"
	@echo "... tools/SpotifyFrameReader.s"
	@echo "... tools/utils.o"
	@echo "... tools/utils.i"
	@echo "... tools/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

